upgrade 'uuid', move more yarn checks into pre-commit, automatically deduplicate yarn.lock (#279)
Follow-up to #275 and #278

Closes #259

* resolves the last remaining dependabot alert, on `uuid`
* adds a `pre-commit` check to automatically run `jlpm dedupe` to minimize how many package versions are stored in `yarn.lock`
* moves more yarn (`jlpm`) checks into `pre-commit`

## Notes for Reviewers

### How I tested this

Cleaned out any not-in-git state.

```console
$ git clean -d -f -X
Removing .eslintcache
Removing .ruff_cache/
Removing .yarn/
Removing jupyterlab_nvdashboard/__pycache__/
Removing jupyterlab_nvdashboard/_version.py
Removing jupyterlab_nvdashboard/apps/__pycache__/
Removing jupyterlab_nvdashboard/labextension/
Removing lib/
Removing node_modules/
Removing tsconfig.tsbuildinfo
```

Manually changed the `yarn` version in `package.json` to 3.6.0 and added a duplicate entry in `yarn.lock`.

```console
$ pre-commit run --all-files check-yarn-version
check-yarn-version.......................................................Failed
- hook id: check-yarn-version
- exit code: 1

error: yarn version from 'jlpm --version' (3.5.0) and 'packageManager' field in package.json (3.6.0) do not match.

$ pre-commit run --all-files yarn-lockfile-dedupe
yarn-lockfile-dedupe.....................................................Failed
- hook id: yarn-lockfile-dedupe
- exit code: 1
... hundreds of lines ...
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 324ms
➤ YN0000: ┌ Link step
➤ YN0007: │ @fortawesome/fontawesome-free@npm:5.15.4 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 2s 856ms
➤ YN0000: Done in 3s 427ms
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ No packages can be deduped using the highest strategy
➤ YN0000: └ Completed
```

Manually reset the version in `package.json`. No manual changes needed in `yarn.lock`, the hook automatically updated it.

```console
$ pre-commit run --all-files
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
ruff check...............................................................Passed
ruff format..............................................................Passed
shellcheck...............................................................Passed
verify-copyright.........................................................Passed
RAPIDS dependency file generator.........................................Passed
zizmor...................................................................Passed
prettier.................................................................Passed
eslint...................................................................Passed
check-yarn-version.......................................................Passed
yarn-lockfile-dedupe.....................................................Passed
check-frontend...........................................................Passed
```

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Naty Clementi (https://github.com/ncclementi)
  - Bradley Dice (https://github.com/bdice)

URL: https://github.com/rapidsai/jupyterlab-nvdashboard/pull/279